"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import jsPDF from "jspdf";
import toast from "react-hot-toast";
import { IconCalculator, IconDownload, IconPlus, IconTrash } from "@tabler/icons-react";
import { Dialog } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { EmptyState } from "@/components/shared/EmptyState";
import { SUBJECTS } from "@/lib/constants";

interface FormulaItem {
  _id: string;
  formulaText: string;
  formulaName: string;
  chapter: string;
  sourceNoteId?: string | null;
  sourceNoteTitle?: string;
  addedAt?: string;
  isManual?: boolean;
}

interface FormulaSheet {
  _id: string;
  subject: string;
  formulas: FormulaItem[];
}

interface QuickQuiz {
  question: string;
  options: Record<"A" | "B" | "C" | "D", string>;
  correct: "A" | "B" | "C" | "D";
  explanation: string;
}

const EMPTY_FORM = {
  formulaText: "",
  formulaName: "",
  subject: "Mathematics",
  chapter: ""
};

export function FormulaSheetPage() {
  const [sheets, setSheets] = useState<FormulaSheet[]>([]);
  const [subject, setSubject] = useState("all");
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState(EMPTY_FORM);
  const [quizOpen, setQuizOpen] = useState(false);
  const [quiz, setQuiz] = useState<QuickQuiz[]>([]);
  const [loadingQuiz, setLoadingQuiz] = useState(false);

  async function load() {
    const response = await fetch("/api/formula-sheet?subject=all", { cache: "no-store" });
    const data = await response.json();
    if (response.ok) {
      setSheets(data.sheets ?? []);
    }
  }

  useEffect(() => {
    void load();
  }, []);

  const filteredSheets = useMemo(() => (subject === "all" ? sheets : sheets.filter((sheet) => sheet.subject === subject)), [sheets, subject]);
  const formulas = useMemo(() => filteredSheets.flatMap((sheet) => sheet.formulas.map((formula) => ({ ...formula, subject: sheet.subject }))), [filteredSheets]);

  async function addFormula() {
    const response = await fetch("/api/formula-sheet/extract", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ...form, isManual: true })
    });
    const data = await response.json();
    if (!response.ok) {
      toast.error(data.error ?? "Could not save formula");
      return;
    }
    toast.success(`Formula saved. ${data.formulaCount ?? ""}`.trim());
    setOpen(false);
    setForm(EMPTY_FORM);
    void load();
  }

  async function removeFormula(formulaId: string) {
    const response = await fetch(`/api/formula-sheet/${formulaId}`, { method: "DELETE" });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      toast.error(data.error ?? "Could not delete formula");
      return;
    }
    void load();
  }

  async function generateQuiz() {
    const selectedSubject = subject === "all" ? filteredSheets[0]?.subject : subject;
    if (!selectedSubject) {
      toast.error("Choose a subject with saved formulas first.");
      return;
    }
    setLoadingQuiz(true);
    const response = await fetch("/api/formula-sheet/quiz", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ subject: selectedSubject, count: 10 })
    });
    const data = await response.json();
    setLoadingQuiz(false);
    if (!response.ok) {
      toast.error(data.error ?? "Could not generate quiz");
      return;
    }
    setQuiz(data.questions ?? []);
    setQuizOpen(true);
  }

  function exportPdf() {
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    let x = 40;
    let y = 56;
    const columnWidth = 250;
    const rowHeight = 110;

    doc.setFont("times", "bold");
    doc.setFontSize(22);
    doc.text(subject === "all" ? "StudyOS Formula Sheet" : `${subject} Formula Sheet`, 40, 40);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    formulas.forEach((formula, index) => {
      if (index > 0 && index % 2 === 0) {
        x = 40;
        y += rowHeight + 20;
      } else if (index % 2 === 1) {
        x = 310;
      }
      if (y > 720) {
        doc.addPage();
        x = 40;
        y = 56;
      }

      doc.roundedRect(x, y, columnWidth, rowHeight, 12, 12);
      doc.setFont("courier", "bold");
      doc.setFontSize(14);
      doc.text(formula.formulaText.slice(0, 45), x + 14, y + 26);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.text(formula.formulaName || "Formula", x + 14, y + 48);
      doc.setFont("helvetica", "normal");
      doc.text(`${formula.subject} • ${formula.chapter || "General"}`, x + 14, y + 66);
    });

    doc.setFontSize(9);
    doc.text("Generated by StudyOS", 40, 810);
    doc.save("studyos-formula-sheet.pdf");
  }

  return (
    <div className="grid gap-5 xl:grid-cols-[240px_1fr]">
      <aside className="glass-card h-fit space-y-4 p-4">
        <button
          type="button"
          onClick={() => setSubject("all")}
          className={`w-full rounded-[18px] px-4 py-3 text-left text-sm font-medium ${subject === "all" ? "bg-[#7B6CF6] text-white" : "surface-card text-[var(--foreground)]"}`}
        >
          All Subjects
        </button>
        {sheets.map((sheet) => (
          <button
            key={sheet._id}
            type="button"
            onClick={() => setSubject(sheet.subject)}
            className={`flex w-full items-center justify-between rounded-[18px] px-4 py-3 text-left text-sm font-medium ${subject === sheet.subject ? "bg-[#7B6CF6] text-white" : "surface-card text-[var(--foreground)]"}`}
          >
            <span>{sheet.subject}</span>
            <span className="rounded-full bg-black/10 px-2 py-0.5 text-xs">{sheet.formulas.length}</span>
          </button>
        ))}
        <Button onClick={() => setOpen(true)} className="w-full rounded-full">
          <IconPlus className="mr-2 h-4 w-4" />
          Add Formula Manually
        </Button>
      </aside>

      <div className="space-y-5">
        <div className="flex flex-wrap items-end justify-between gap-3">
          <div>
            <p className="text-[11px] font-medium uppercase tracking-[0.16em] text-[var(--tertiary-foreground)]">Collection</p>
            <h2 className="mt-2 font-headline text-4xl tracking-[-0.04em] text-[var(--foreground)] sm:text-6xl">
              {subject === "all" ? "Formula Sheet" : subject}
            </h2>
          </div>
          <div className="flex flex-wrap gap-2">
            <Button variant="outline" onClick={exportPdf}>
              <IconDownload className="mr-2 h-4 w-4" />
              Export as PDF
            </Button>
            <Button onClick={() => void generateQuiz()} disabled={loadingQuiz}>
              <IconCalculator className="mr-2 h-4 w-4" />
              {loadingQuiz ? "Preparing..." : "Quiz Me on Formulas"}
            </Button>
          </div>
        </div>

        {formulas.length === 0 ? (
          <EmptyState
            title="No formulas yet"
            description="Generate notes to auto-collect formulas, or add them manually."
            actionLabel="Add Formula"
            onAction={() => setOpen(true)}
          />
        ) : (
          <div className="grid gap-4 md:grid-cols-2">
            {formulas.map((formula) => (
              <div key={formula._id} className="glass-card relative rounded-[28px] p-5">
                <button
                  type="button"
                  onClick={() => void removeFormula(formula._id)}
                  className="surface-icon absolute right-4 top-4 inline-flex h-10 w-10 items-center justify-center rounded-full text-[#B91C1C]"
                >
                  <IconTrash className="h-4 w-4" />
                </button>
                <p className="mt-4 text-center font-mono text-lg text-[var(--foreground)]">{formula.formulaText}</p>
                <p className="mt-4 text-center text-base font-semibold text-[var(--foreground)]">{formula.formulaName || "Formula"}</p>
                <div className="mt-4 flex flex-wrap items-center justify-center gap-2">
                  <span className="rounded-full bg-[#7B6CF6]/12 px-3 py-1 text-xs font-medium text-[#7B6CF6]">{formula.chapter || "General"}</span>
                  <span className="rounded-full bg-[color:var(--surface-low)] px-3 py-1 text-xs text-[var(--muted-foreground)]">
                    {(formula as FormulaItem & { subject: string }).subject}
                  </span>
                </div>
                <div className="mt-4 text-center">
                  {formula.sourceNoteId ? (
                    <Link href={`/notes/${formula.sourceNoteId}`} className="text-sm text-[#7B6CF6]">
                      From: {formula.sourceNoteTitle || "Linked note"}
                    </Link>
                  ) : (
                    <span className="text-sm text-[var(--muted-foreground)]">Added manually</span>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      <Dialog
        open={open}
        onClose={() => setOpen(false)}
        title="Add Formula"
        size="sm"
        footer={
          <div className="flex justify-end gap-2">
            <Button variant="outline" onClick={() => setOpen(false)}>
              Cancel
            </Button>
            <Button onClick={addFormula}>Save Formula</Button>
          </div>
        }
      >
        <div className="space-y-4">
          <div>
            <label className="mb-2 block text-sm font-medium text-[var(--foreground)]">Formula Text</label>
            <Input value={form.formulaText} onChange={(event) => setForm((prev) => ({ ...prev, formulaText: event.target.value }))} />
          </div>
          <div>
            <label className="mb-2 block text-sm font-medium text-[var(--foreground)]">Formula Name</label>
            <Input value={form.formulaName} onChange={(event) => setForm((prev) => ({ ...prev, formulaName: event.target.value }))} />
          </div>
          <div>
            <label className="mb-2 block text-sm font-medium text-[var(--foreground)]">Subject</label>
            <Select value={form.subject} onChange={(event) => setForm((prev) => ({ ...prev, subject: event.target.value }))}>
              {SUBJECTS.map((item) => (
                <option key={item} value={item}>
                  {item}
                </option>
              ))}
            </Select>
          </div>
          <div>
            <label className="mb-2 block text-sm font-medium text-[var(--foreground)]">Chapter</label>
            <Input value={form.chapter} onChange={(event) => setForm((prev) => ({ ...prev, chapter: event.target.value }))} />
          </div>
        </div>
      </Dialog>

      <Dialog open={quizOpen} onClose={() => setQuizOpen(false)} title="Formula Quiz" size="lg">
        <div className="space-y-4">
          {quiz.map((question, index) => (
            <div key={`${question.question}-${index}`} className="surface-card rounded-[22px] p-4">
              <p className="font-semibold text-[var(--foreground)]">
                {index + 1}. {question.question}
              </p>
              <div className="mt-3 grid gap-2 md:grid-cols-2">
                {Object.entries(question.options).map(([key, value]) => (
                  <div key={key} className={`rounded-[18px] border px-3 py-2 text-sm ${key === question.correct ? "border-[#34D399] bg-[#34D399]/10 text-[#0F766E]" : "border-[color:var(--panel-border)] text-[var(--muted-foreground)]"}`}>
                    {key}. {value}
                  </div>
                ))}
              </div>
              <p className="mt-3 text-sm leading-6 text-[var(--muted-foreground)]">{question.explanation}</p>
            </div>
          ))}
        </div>
      </Dialog>
    </div>
  );
}
